In [1]:
import pandas as pd
import pandas as pd

df = pd.read_csv("shopping_trends-selected-columns.csv")

print(df.head())

   Customer ID  Age Gender Item Purchased  Category  Purchase Amount (USD)
0            1   55   Male         Blouse  Clothing                     53
1            2   19   Male        Sweater  Clothing                     64
2            3   50   Male          Jeans  Clothing                     73
3            4   21   Male        Sandals  Footwear                     90
4            5   45   Male         Blouse  Clothing                     49

In [2]:
print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3900 entries, 0 to 3899
Data columns (total 6 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Customer ID            3900 non-null   int64
 1   Age                    3900 non-null   int64
 2   Gender                 3900 non-null   object
 3   Item Purchased         3900 non-null   object
 4   Category               3900 non-null   object
 5   Purchase Amount (USD)  3900 non-null   int64
dtypes: int64(3), object(3)
memory usage: 182.9+ KB
None

In [4]:
df[["Age", "Purchase Amount (USD)"]].describe()

               Age  Purchase Amount (USD)
count  3900.000000            3900.000000
mean     44.068462              59.764359
std      15.207589              23.685392
min      18.000000              20.000000
25%      31.000000              39.000000
50%      44.000000              60.000000
75%      57.000000              81.000000
max      70.000000             100.000000

In [ ]:
df.sort_values("Purchase Amount (USD)" , ascending = False)#büyükten küçüğe sıralama ascending = False

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD)
2842,2843,28,Female,Coat,Outerwear,100
95,96,37,Male,Sneakers,Footwear,100
581,582,32,Male,Sweater,Clothing,100
1421,1422,68,Male,Dress,Clothing,100
3837,3838,45,Female,Hoodie,Clothing,100
...,...,...,...,...,...,...
1704,1705,56,Male,Sneakers,Footwear,20
294,295,70,Male,Skirt,Clothing,20
977,978,20,Male,Belt,Accessories,20
508,509,27,Male,Jewelry,Accessories,20
2798,2799,52,Female,Hoodie,Clothing,20

In [11]:
df.sort_values("Purchase Amount (USD)" , ascending = False).head(5)

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD)
2842,2843,28,Female,Coat,Outerwear,100
95,96,37,Male,Sneakers,Footwear,100
581,582,32,Male,Sweater,Clothing,100
1421,1422,68,Male,Dress,Clothing,100
3837,3838,45,Female,Hoodie,Clothing,100

In [21]:
df.groupby("Category")["Purchase Amount (USD)"].mean().sort_values(ascending=False).head(1)

Category
Footwear    60.255426
Name: Purchase Amount (USD), dtype: float64

In [23]:
df.groupby(["Gender", "Category"])["Purchase Amount (USD)"].mean().sort_values(ascending = False).head(1)

Gender  Category
Female  Accessories    60.762755
Name: Purchase Amount (USD), dtype: float64

In [24]:
df["Age Group"] = pd.cut(
    df["Age"],
    bins=[17, 29, 44, 59, 70],
    labels=["Genç", "Orta yaş", "İleri yaş", "60+"]
)

In [25]:
df[["Age", "Age Group"]].head(10)

   Age  Age Group
0   55  İleri yaş
1   19       Genç
2   50  İleri yaş
3   21       Genç
4   45  İleri yaş
5   46  İleri yaş
6   63        60+
7   27       Genç
8   26       Genç
9   57  İleri yaş

In [28]:
df.groupby("Age Group")["Purchase Amount (USD)"].mean().sort_values(ascending = False).head(1)

C:\Users\esmah\AppData\Local\Temp\ipykernel_5424\3213516478.py:1: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  df.groupby("Age Group")["Purchase Amount (USD)"].mean().sort_values(ascending = False).head(1)

Age Group
Genç    60.256264
Name: Purchase Amount (USD), dtype: float64

In [29]:
df.groupby(["Gender", "Category"])["Purchase Amount (USD)"].mean().sort_values(ascending = False).head(1)

Gender  Category
Female  Accessories    60.762755
Name: Purchase Amount (USD), dtype: float64